services:
    ad-service:
        build: 
            context: ./ad-service
            dockerfile: Dockerfile
            additional_contexts:
                common: ./common
        ports: ["8081:8081"]
        networks:
            - default
        depends_on:
            - postgres

    user-service:
        build:
            context: ./user-service
            dockerfile: Dockerfile
            additional_contexts:
                common: ./common
        ports: ["8082:8082"]
        networks:
            - default
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        user: postgres
        restart: always
        environment:
            POSTGRES_DB: storage
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - default
        ports: ["5434:5432"]
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "storage"]
            interval: 5s
            timeout: 5s
            retries: 10
  