version: "1.0.0"

services:
    ad-service:
        build: ./ad-service
        ports: ["8081:8081"]
        networks:
            - default
        depends_on:
            - postgres

    user-service:
        build: ./user-service
        ports: ["8082:8082"]
        networks:
            - default
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        user: postgres
        restart: always
        environment:
            POSTGRES_DB: storage
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        networks:
            - default
        ports: ["5434:5432"]
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "storage"]
            interval: 5s
            timeout: 5s
            retries: 10
  